import { create } from 'zustand'
import type { Entity } from '@/lib/types'

interface EntityState {
	entities: Record<string, Entity>
	focusedId: string | null
	upsert: (entity: Entity) => void
	remove: (id: string) => void
	bumpZIndex: (id: string) => void
	setFocused: (id: string | null) => void
	updatePosition: (id: string, pos: { x: number; y: number }) => void
	updateSize: (id: string, size: { width: number; height: number }) => void
	updateContent: (id: string, content: string) => void
	loadMockData: () => void
	getEntity: (id: string) => Entity | undefined
	getEntitiesSorted: () => Entity[]
	getVisibleEntities: () => Entity[]
}

export const useEntityStore = create<EntityState>((set, get) => ({
	entities: {},
	focusedId: null,

	upsert: (entity) => {
		set((state) => ({
			entities: { ...state.entities, [entity.id]: entity },
		}))
	},

	remove: (id) => {
		set((state) => {
			const { [id]: _, ...rest } = state.entities
			return { entities: rest }
		})
	},

	bumpZIndex: (id) => {
		const { entities } = get()
		const entity = entities[id]
		if (!entity) return

		const maxZ = Math.max(...Object.values(entities).map((e) => e.z_index))
		if (entity.z_index >= maxZ) return

		set((state) => ({
			entities: {
				...state.entities,
				[id]: { ...state.entities[id], z_index: maxZ + 1 },
			},
		}))
	},

	setFocused: (id) => {
		if (id) {
			get().bumpZIndex(id)
		}
		set({ focusedId: id })
	},

	updatePosition: (id, pos) => {
		const entity = get().entities[id]
		if (!entity) return

		set((state) => ({
			entities: {
				...state.entities,
				[id]: {
					...state.entities[id],
					position: { x: pos.x, y: pos.y, locked: true },
				},
			},
		}))
	},

	updateSize: (id, size) => {
		const entity = get().entities[id]
		if (!entity) return

		set((state) => ({
			entities: {
				...state.entities,
				[id]: {
					...state.entities[id],
					size: {
						width: Math.max(size.width, 300),
						height: Math.max(size.height, 200),
					},
				},
			},
		}))
	},

	updateContent: (id, content) => {
		const entity = get().entities[id]
		if (!entity) return

		set((state) => ({
			entities: {
				...state.entities,
				[id]: { ...state.entities[id], content, updated_at: new Date().toISOString() },
			},
		}))
	},

	loadMockData: () => {
		const mockEntities: Entity[] = [
			{
				id: 'mock-note-window',
				space_id: 'mock-space',
				user_id: 'mock-user',
				type: 'note',
				presentation: 'window',
				position: { x: 40, y: 40, locked: false },
				size: { width: 500, height: 400 },
				z_index: 1,
				content:
					'# Welcome to Domus\n\nThis is a sample note rendered as a window. Scroll down to see the edge-fade effect under the floating header.\n\n---\n\nDomus treats every piece of information as a spatial entity — notes, images, conversations, and agent outputs all live on an infinite canvas. You arrange them however makes sense to you.\n\n## Design Principles\n\nContent should feel physical. Windows have weight, surfaces have depth, and everything grows from an origin point. Nothing pops into existence.\n\nThe canvas is yours. The agent assists, but you decide what stays, what moves, and what disappears.\n\n## Try It\n\nDrag this window around. Resize it from the edges. Notice how the content scrolls underneath the controls at the top — no hard separator, just a gentle fade.',
				state: {},
				summary: 'Welcome note',
				created_by: 'user',
				archived: false,
				created_at: '2026-02-15T10:00:00Z',
				updated_at: '2026-02-15T10:00:00Z',
			},
			{
				id: 'mock-note-card',
				space_id: 'mock-space',
				user_id: 'mock-user',
				type: 'note',
				presentation: 'card',
				position: { x: 600, y: 60, locked: false },
				size: { width: 280, height: 200 },
				z_index: 2,
				content: 'Quick thoughts about the project direction.',
				state: {},
				summary: 'Project thoughts',
				created_by: 'user',
				archived: false,
				created_at: '2026-02-15T11:00:00Z',
				updated_at: '2026-02-15T11:00:00Z',
			},
			{
				id: 'mock-agent-note',
				space_id: 'mock-space',
				user_id: 'mock-user',
				type: 'note',
				presentation: 'window',
				position: { x: 300, y: 320, locked: false },
				size: { width: 450, height: 350 },
				z_index: 3,
				content:
					'## Research Summary\n\nHere are the key findings from the analysis.\n\n### 1. Spatial interfaces reduce cognitive load\n\nWhen information is arranged in space rather than stacked in a timeline, users recall context faster. Studies on spatial memory show 40% better retrieval when items have a stable location.\n\n### 2. Agent output needs grounding\n\nAI-generated content that appears without spatial context feels disconnected. Anchoring agent output to the canvas — near the entities that prompted it — keeps the conversation grounded.\n\n### 3. Progressive disclosure beats dashboards\n\nRather than showing everything at once, let users drill into detail on demand. Cards summarise, windows elaborate, sheets immerse.\n\n---\n\n*Generated by the Domus space agent based on three research papers and one design review.*',
				state: {},
				summary: 'Research summary',
				created_by: 'agent',
				archived: false,
				created_at: '2026-02-15T12:00:00Z',
				updated_at: '2026-02-15T12:00:00Z',
			},
			{
				id: 'mock-chat-window',
				space_id: 'mock-space',
				user_id: 'mock-user',
				type: 'chat',
				presentation: 'window',
				position: { x: 580, y: 300, locked: false },
				size: { width: 400, height: 500 },
				z_index: 4,
				content: '',
				state: {},
				summary: 'Chat conversation',
				created_by: 'user',
				archived: false,
				created_at: '2026-02-16T10:00:00Z',
				updated_at: '2026-02-16T10:00:00Z',
			},
			{
				id: 'mock-calendar-window',
				space_id: 'mock-space',
				user_id: 'mock-user',
				type: 'calendar',
				presentation: 'window',
				position: { x: 100, y: 350, locked: false },
				size: { width: 500, height: 450 },
				z_index: 5,
				content: '',
				state: {},
				summary: 'Calendar',
				created_by: 'user',
				archived: false,
				created_at: '2026-02-16T10:00:00Z',
				updated_at: '2026-02-16T10:00:00Z',
			},
			{
				id: 'mock-hidden',
				space_id: 'mock-space',
				user_id: 'mock-user',
				type: 'conversation_turn',
				presentation: 'hidden',
				position: { x: 0, y: 0, locked: false },
				size: { width: 0, height: 0 },
				z_index: 0,
				content: '',
				state: { role: 'user', content: 'hello' },
				summary: 'User greeting',
				created_by: 'user',
				archived: false,
				created_at: '2026-02-15T09:00:00Z',
				updated_at: '2026-02-15T09:00:00Z',
			},
		]

		const entities: Record<string, Entity> = {}
		for (const e of mockEntities) {
			if (e.presentation !== 'hidden') {
				entities[e.id] = e
			}
		}
		set({ entities })
	},

	getEntity: (id) => {
		return get().entities[id]
	},

	getEntitiesSorted: () => {
		return Object.values(get().entities).sort((a, b) => a.z_index - b.z_index)
	},

	getVisibleEntities: () => {
		return Object.values(get().entities).filter((e) => e.presentation !== 'hidden')
	},
}))
